version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install libsass
sphinx:
   configuration: docs/conf.py
python:
   install:
   - method: pip
     path: .
     extra_requirements:
       - docs
